/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Adrian
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void ControlaUbicacion(JInternalFrame inter) {
        boolean m = true;
        String Nombre = inter.getTitle();
        for (int i = 0; i < jDesktopPane1.getComponentCount(); i++) {
            if (inter.getClass().isInstance(jDesktopPane1.getComponent(i))) {
                inter.toFront();
                jDesktopPane1.moveToFront(inter);
                m = false;
            } 
        }
        if (m) {
            jDesktopPane1.add(inter);
            Dimension destopSize = jDesktopPane1.getSize();
            Dimension frame = inter.getSize();
            inter.setLocation((destopSize.width - frame.width) / 2, (destopSize.height - frame.height) / 2);
        }
        inter.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        btnProductosProveedores = new javax.swing.JMenu();
        btnCategorias = new javax.swing.JMenuItem();
        btnClientes = new javax.swing.JMenuItem();
        btnContactos = new javax.swing.JMenuItem();
        btnEstados = new javax.swing.JMenuItem();
        btnLocalidades = new javax.swing.JMenuItem();
        btnMunicipios = new javax.swing.JMenuItem();
        btnProductos = new javax.swing.JMenuItem();
        btnProductoProveedor = new javax.swing.JMenuItem();
        btnProveedores = new javax.swing.JMenuItem();
        btnSucursales = new javax.swing.JMenuItem();
        btnUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        btnProductosProveedores.setText("Catalogos");

        btnCategorias.setText("Categorias");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnCategorias);

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnClientes);

        btnContactos.setText("Contactos");
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnContactos);

        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnEstados);

        btnLocalidades.setText("Localidades");
        btnLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalidadesActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnLocalidades);

        btnMunicipios.setText("Municipios");
        btnMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipiosActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnMunicipios);

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnProductos);

        btnProductoProveedor.setText("Productos Proveedores");
        btnProductoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoProveedorActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnProductoProveedor);

        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnProveedores);

        btnSucursales.setText("Sucursales");
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnSucursales);

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        btnProductosProveedores.add(btnUsuarios);

        jMenuBar1.add(btnProductosProveedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        frmCategorias obj = new frmCategorias();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        frmClientes obj = new frmClientes();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        frmContactos obj = new frmContactos();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        frmEstados obj = new frmEstados();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalidadesActionPerformed
        frmLocalidades obj = new frmLocalidades();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnLocalidadesActionPerformed

    private void btnMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipiosActionPerformed
        frmMunicipios obj = new frmMunicipios();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnMunicipiosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        frmProductos obj = new frmProductos();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnProductoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoProveedorActionPerformed
        frmProductosProveedores obj = new frmProductosProveedores();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnProductoProveedorActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        frmProveedores obj = new frmProveedores();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        frmSucursales obj = new frmSucursales();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnSucursalesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        frmUsuarios obj = new frmUsuarios();
        ControlaUbicacion(obj);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCategorias;
    private javax.swing.JMenuItem btnClientes;
    private javax.swing.JMenuItem btnContactos;
    private javax.swing.JMenuItem btnEstados;
    private javax.swing.JMenuItem btnLocalidades;
    private javax.swing.JMenuItem btnMunicipios;
    private javax.swing.JMenuItem btnProductoProveedor;
    private javax.swing.JMenuItem btnProductos;
    private javax.swing.JMenu btnProductosProveedores;
    private javax.swing.JMenuItem btnProveedores;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnSucursales;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
